### ISSUE TITLE
'Clean' picosoc for Upduino (v2.0)?

### ISSUE THREAD

**Issue by ghost** [mmicko/mikrobus-upduino#2]
Hi!

It looks like you built this, and a micropython port for Upduino around picorv32/picosoc.
Is there any chance you have a 'clean' picorv32/picosoc that's configured for the Upduino v2.0? :)

I'm guessing the icebreaker version would be very very close, but since I'm just new to FPGA I'm not sure exactly what I need to change yet :)

My plan is to stick it in a Upduino v2.0 board, use the onboard 12mhz crystal connected to a GBIN pin as clock source, and connect a CP2102 to two regular PIO pins for serial in/out :)

I know it's a far shot, thanks in advance regardless! :)

**Comment by ghost** [comment]
Hmm, I'm realizing that the port in https://github.com/mmicko/micropython/tree/legacy/ports/picorv32 is actually very close to what I want :)

**Comment by ghost** [comment]
Ok, I've created my own 'clean' picosoc for Upduino v2.0 :)
Changes were pretty minimal from the icebreaker version, results are now here: https://github.com/cranphin/picorv32
Guess this issue can be closed ^_^

**Comment by mmicko** [comment]
Sorry for not responding in proper time, was quite busy. Glad you have managed to make it work on your environment and that you have find it useful :)
